version: "3.7"

services:
  django:
    image: django_backend:v0
    restart: unless-stopped
    build:
      context: .
      args:
        DJANGO_DEBUG: "True"
        DJANGO_SENTRY_DSN: $DJANGO_SENTRY_DSN
        DJANGO_SENTRY_RELEASE: $DJANGO_SENTRY_RELEASE
        DJANGO_SENTRY_ENVIRONMENT: $DJANGO_SENTRY_ENVIRONMENT
        DJANGO_SENTRY_TRACES_SAMPLE_RATE: $DJANGO_SENTRY_TRACES_SAMPLE_RATE
    ports:
      - "8000:8000"

  react:
    image: react_frontend:v0
    environment:
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
      - REACT_APP_SENTRY_RELEASE=${REACT_APP_SENTRY_RELEASE}
      - REACT_APP_SENTRY_ENVIRONMENT=${REACT_APP_SENTRY_ENVIRONMENT}
      - REACT_APP_SENTRY_TRACES_SAMPLE_RATE=${REACT_APP_SENTRY_TRACES_SAMPLE_RATE}
    restart: unless-stopped
    build:
      context: ./app/
    ports:
      - "3000:3000"
